import gql from "graphql-tag";
import * as VueApolloComposable from "@vue/apollo-composable";
import type * as VueCompositionApi from "vue";
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
export type ReactiveFunction<TParam> = () => TParam;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  ISO8601DateTime: { input: string; output: string };
};

/** Autogenerated input type of AcceptConnectionRequest */
export type AcceptConnectionRequestInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars["String"]["input"]>;
  connectionId: Scalars["ID"]["input"];
};

/** Autogenerated return type of AcceptConnectionRequest. */
export type AcceptConnectionRequestPayload = {
  __typename?: "AcceptConnectionRequestPayload";
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars["String"]["output"]>;
  errors: Array<Scalars["String"]["output"]>;
  success: Scalars["Boolean"]["output"];
};

export type Company = {
  __typename?: "Company";
  description: Maybe<Scalars["String"]["output"]>;
  headquarters: Scalars["String"]["output"];
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
  slug: Scalars["String"]["output"];
  /** Return a paginated list of users */
  users: UserConnection;
};

export type CompanyUsersArgs = {
  after: InputMaybe<Scalars["String"]["input"]>;
  before: InputMaybe<Scalars["String"]["input"]>;
  first: InputMaybe<Scalars["Int"]["input"]>;
  last: InputMaybe<Scalars["Int"]["input"]>;
};

/** The connection type for Company. */
export type CompanyConnection = {
  __typename?: "CompanyConnection";
  /** A list of edges. */
  edges: Maybe<Array<Maybe<CompanyEdge>>>;
  /** A list of nodes. */
  nodes: Maybe<Array<Maybe<Company>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type CompanyEdge = {
  __typename?: "CompanyEdge";
  /** A cursor for use in pagination. */
  cursor: Scalars["String"]["output"];
  /** The item at the end of the edge. */
  node: Maybe<Company>;
};

export type Connection = {
  __typename?: "Connection";
  createdAt: Scalars["ISO8601DateTime"]["output"];
  id: Scalars["ID"]["output"];
  /** The user who received the connection request */
  recipient: User;
  recipientId: Scalars["Int"]["output"];
  /** The user who sent the connection request */
  requester: User;
  requesterId: Scalars["Int"]["output"];
  status: Scalars["String"]["output"];
  updatedAt: Scalars["ISO8601DateTime"]["output"];
};

/** Autogenerated input type of DeclineConnectionRequest */
export type DeclineConnectionRequestInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars["String"]["input"]>;
  connectionId: Scalars["ID"]["input"];
};

/** Autogenerated return type of DeclineConnectionRequest. */
export type DeclineConnectionRequestPayload = {
  __typename?: "DeclineConnectionRequestPayload";
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars["String"]["output"]>;
  errors: Array<Scalars["String"]["output"]>;
  success: Scalars["Boolean"]["output"];
};

export type Mutation = {
  __typename?: "Mutation";
  acceptConnectionRequest: Maybe<AcceptConnectionRequestPayload>;
  declineConnectionRequest: Maybe<DeclineConnectionRequestPayload>;
  removeConnection: Maybe<RemoveConnectionPayload>;
  sendConnectionRequest: Maybe<SendConnectionRequestPayload>;
};

export type MutationAcceptConnectionRequestArgs = {
  input: AcceptConnectionRequestInput;
};

export type MutationDeclineConnectionRequestArgs = {
  input: DeclineConnectionRequestInput;
};

export type MutationRemoveConnectionArgs = {
  input: RemoveConnectionInput;
};

export type MutationSendConnectionRequestArgs = {
  input: SendConnectionRequestInput;
};

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: "PageInfo";
  /** When paginating forwards, the cursor to continue. */
  endCursor: Maybe<Scalars["String"]["output"]>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars["Boolean"]["output"];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars["Boolean"]["output"];
  /** When paginating backwards, the cursor to continue. */
  startCursor: Maybe<Scalars["String"]["output"]>;
};

export type Query = {
  __typename?: "Query";
  /** Return a paginated list of companies */
  companies: CompanyConnection;
  /** Find a company by slug */
  company: Maybe<Company>;
  /** Find a user by slug */
  user: Maybe<User>;
  /** Return a paginated list of users */
  users: UserConnection;
};

export type QueryCompaniesArgs = {
  after: InputMaybe<Scalars["String"]["input"]>;
  before: InputMaybe<Scalars["String"]["input"]>;
  first: InputMaybe<Scalars["Int"]["input"]>;
  last: InputMaybe<Scalars["Int"]["input"]>;
};

export type QueryCompanyArgs = {
  slug: Scalars["String"]["input"];
};

export type QueryUserArgs = {
  slug: Scalars["String"]["input"];
};

export type QueryUsersArgs = {
  after: InputMaybe<Scalars["String"]["input"]>;
  before: InputMaybe<Scalars["String"]["input"]>;
  first: InputMaybe<Scalars["Int"]["input"]>;
  last: InputMaybe<Scalars["Int"]["input"]>;
};

/** Autogenerated input type of RemoveConnection */
export type RemoveConnectionInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars["String"]["input"]>;
  connectionId: Scalars["ID"]["input"];
};

/** Autogenerated return type of RemoveConnection. */
export type RemoveConnectionPayload = {
  __typename?: "RemoveConnectionPayload";
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars["String"]["output"]>;
  errors: Array<Scalars["String"]["output"]>;
  success: Scalars["Boolean"]["output"];
};

/** Autogenerated input type of SendConnectionRequest */
export type SendConnectionRequestInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: InputMaybe<Scalars["String"]["input"]>;
  recipientId: Scalars["ID"]["input"];
  requesterId: Scalars["ID"]["input"];
};

/** Autogenerated return type of SendConnectionRequest. */
export type SendConnectionRequestPayload = {
  __typename?: "SendConnectionRequestPayload";
  /** A unique identifier for the client performing the mutation. */
  clientMutationId: Maybe<Scalars["String"]["output"]>;
  errors: Array<Scalars["String"]["output"]>;
  success: Scalars["Boolean"]["output"];
};

export type User = {
  __typename?: "User";
  company: Company;
  companyId: Scalars["Int"]["output"];
  /** All accepted connections for this user */
  connections: Maybe<Array<User>>;
  /** The post-nominal letters (e.g., M.D.) for the user */
  credentials: Maybe<Scalars["String"]["output"]>;
  firstName: Scalars["String"]["output"];
  id: Scalars["ID"]["output"];
  lastName: Scalars["String"]["output"];
  middleName: Maybe<Scalars["String"]["output"]>;
  nickname: Maybe<Scalars["String"]["output"]>;
  /** Pending connection requests received by this user */
  pendingReceivedRequests: Maybe<Array<Connection>>;
  /** Pending connection requests sent by this user */
  pendingSentRequests: Maybe<Array<Connection>>;
  slug: Scalars["String"]["output"];
};

/** The connection type for User. */
export type UserConnection = {
  __typename?: "UserConnection";
  /** A list of edges. */
  edges: Maybe<Array<Maybe<UserEdge>>>;
  /** A list of nodes. */
  nodes: Maybe<Array<Maybe<User>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type UserEdge = {
  __typename?: "UserEdge";
  /** A cursor for use in pagination. */
  cursor: Scalars["String"]["output"];
  /** The item at the end of the edge. */
  node: Maybe<User>;
};

export type GetCompanyQueryVariables = Exact<{
  slug: Scalars["String"]["input"];
  first?: InputMaybe<Scalars["Int"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
}>;

export type GetCompanyQuery = {
  __typename?: "Query";
  company: {
    __typename?: "Company";
    slug: string;
    name: string;
    headquarters: string;
    description: string | null;
    users: {
      __typename?: "UserConnection";
      edges: Array<{
        __typename?: "UserEdge";
        cursor: string;
        node: {
          __typename?: "User";
          slug: string;
          firstName: string;
          lastName: string;
          credentials: string | null;
        } | null;
      } | null> | null;
      pageInfo: {
        __typename?: "PageInfo";
        hasNextPage: boolean;
        hasPreviousPage: boolean;
        startCursor: string | null;
        endCursor: string | null;
      };
    };
  } | null;
};

export type GetUserQueryVariables = Exact<{
  slug: Scalars["String"]["input"];
}>;

export type GetUserQuery = {
  __typename?: "Query";
  user: {
    __typename?: "User";
    slug: string;
    firstName: string;
    lastName: string;
    credentials: string | null;
    company: { __typename?: "Company"; slug: string; name: string };
  } | null;
};

export type GetUsersQueryVariables = Exact<{
  first?: InputMaybe<Scalars["Int"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
}>;

export type GetUsersQuery = {
  __typename?: "Query";
  users: {
    __typename?: "UserConnection";
    edges: Array<{
      __typename?: "UserEdge";
      cursor: string;
      node: {
        __typename?: "User";
        slug: string;
        firstName: string;
        lastName: string;
        credentials: string | null;
      } | null;
    } | null> | null;
    pageInfo: {
      __typename?: "PageInfo";
      startCursor: string | null;
      endCursor: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
  };
};

export const GetCompanyDocument = gql`
  query GetCompany($slug: String!, $first: Int = 10, $after: String = null) {
    company(slug: $slug) {
      slug
      name
      headquarters
      description
      users(first: $first, after: $after) {
        edges {
          node {
            slug
            firstName
            lastName
            credentials
          }
          cursor
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }
    }
  }
`;

/**
 * __useGetCompanyQuery__
 *
 * To run a query within a Vue component, call `useGetCompanyQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetCompanyQuery` returns an object from Apollo Client that contains result, loading and error properties
 * you can use to render your UI.
 *
 * @param variables that will be passed into the query
 * @param options that will be passed into the query, supported options are listed on: https://v4.apollo.vuejs.org/guide-composable/query.html#options;
 *
 * @example
 * const { result, loading, error } = useGetCompanyQuery({
 *   slug: // value for 'slug'
 *   first: // value for 'first'
 *   after: // value for 'after'
 * });
 */
export function useGetCompanyQuery(
  variables:
    | GetCompanyQueryVariables
    | VueCompositionApi.Ref<GetCompanyQueryVariables>
    | ReactiveFunction<GetCompanyQueryVariables>,
  options:
    | VueApolloComposable.UseQueryOptions<
        GetCompanyQuery,
        GetCompanyQueryVariables
      >
    | VueCompositionApi.Ref<
        VueApolloComposable.UseQueryOptions<
          GetCompanyQuery,
          GetCompanyQueryVariables
        >
      >
    | ReactiveFunction<
        VueApolloComposable.UseQueryOptions<
          GetCompanyQuery,
          GetCompanyQueryVariables
        >
      > = {}
) {
  return VueApolloComposable.useQuery<
    GetCompanyQuery,
    GetCompanyQueryVariables
  >(GetCompanyDocument, variables, options);
}
export function useGetCompanyLazyQuery(
  variables?:
    | GetCompanyQueryVariables
    | VueCompositionApi.Ref<GetCompanyQueryVariables>
    | ReactiveFunction<GetCompanyQueryVariables>,
  options:
    | VueApolloComposable.UseQueryOptions<
        GetCompanyQuery,
        GetCompanyQueryVariables
      >
    | VueCompositionApi.Ref<
        VueApolloComposable.UseQueryOptions<
          GetCompanyQuery,
          GetCompanyQueryVariables
        >
      >
    | ReactiveFunction<
        VueApolloComposable.UseQueryOptions<
          GetCompanyQuery,
          GetCompanyQueryVariables
        >
      > = {}
) {
  return VueApolloComposable.useLazyQuery<
    GetCompanyQuery,
    GetCompanyQueryVariables
  >(GetCompanyDocument, variables, options);
}
export type GetCompanyQueryCompositionFunctionResult =
  VueApolloComposable.UseQueryReturn<GetCompanyQuery, GetCompanyQueryVariables>;
export const GetUserDocument = gql`
  query GetUser($slug: String!) {
    user(slug: $slug) {
      slug
      firstName
      lastName
      credentials
      company {
        slug
        name
      }
    }
  }
`;

/**
 * __useGetUserQuery__
 *
 * To run a query within a Vue component, call `useGetUserQuery` and pass it any
 * options that fit your needs. When your component renders, `useGetUserQuery`
 * returns an object from Apollo Client that contains result, loading and error
 * properties you can use to render your UI.
 *
 * @param variables that will be passed into the query
 * @param options that will be passed into the query, supported options are
 * listed on: https://v4.apollo.vuejs.org/guide-composable/query.html#options;
 *
 * @example
 * const { result, loading, error } = useGetUserQuery({
 *   slug: // value for 'slug'
 * });
 */
export function useGetUserQuery(
  variables:
    | GetUserQueryVariables
    | VueCompositionApi.Ref<GetUserQueryVariables>
    | ReactiveFunction<GetUserQueryVariables>,
  options:
    | VueApolloComposable.UseQueryOptions<GetUserQuery, GetUserQueryVariables>
    | VueCompositionApi.Ref<
        VueApolloComposable.UseQueryOptions<GetUserQuery, GetUserQueryVariables>
      >
    | ReactiveFunction<
        VueApolloComposable.UseQueryOptions<GetUserQuery, GetUserQueryVariables>
      > = {}
) {
  return VueApolloComposable.useQuery<GetUserQuery, GetUserQueryVariables>(
    GetUserDocument,
    variables,
    options
  );
}
export function useGetUserLazyQuery(
  variables?:
    | GetUserQueryVariables
    | VueCompositionApi.Ref<GetUserQueryVariables>
    | ReactiveFunction<GetUserQueryVariables>,
  options:
    | VueApolloComposable.UseQueryOptions<GetUserQuery, GetUserQueryVariables>
    | VueCompositionApi.Ref<
        VueApolloComposable.UseQueryOptions<GetUserQuery, GetUserQueryVariables>
      >
    | ReactiveFunction<
        VueApolloComposable.UseQueryOptions<GetUserQuery, GetUserQueryVariables>
      > = {}
) {
  return VueApolloComposable.useLazyQuery<GetUserQuery, GetUserQueryVariables>(
    GetUserDocument,
    variables,
    options
  );
}
export type GetUserQueryCompositionFunctionResult =
  VueApolloComposable.UseQueryReturn<GetUserQuery, GetUserQueryVariables>;
export const GetUsersDocument = gql`
  query GetUsers($first: Int = 10, $after: String = null) {
    users(first: $first, after: $after) {
      edges {
        node {
          slug
          firstName
          lastName
          credentials
        }
        cursor
      }
      pageInfo {
        startCursor
        endCursor
        hasNextPage
        hasPreviousPage
      }
    }
  }
`;

/**
 * __useGetUsersQuery__
 *
 * To run a query within a Vue component, call `useGetUsersQuery` and pass it
 * any options that fit your needs. When your component renders,
 * `useGetUsersQuery` returns an object from Apollo Client that contains result,
 * loading and error properties you can use to render your UI.
 *
 * @param variables that will be passed into the query
 * @param options that will be passed into the query, supported options are
 * listed on: https://v4.apollo.vuejs.org/guide-composable/query.html#options;
 *
 * @example
 * const { result, loading, error } = useGetUsersQuery({
 *   first: // value for 'first'
 *   after: // value for 'after'
 * });
 */
export function useGetUsersQuery(
  variables:
    | GetUsersQueryVariables
    | VueCompositionApi.Ref<GetUsersQueryVariables>
    | ReactiveFunction<GetUsersQueryVariables> = {},
  options:
    | VueApolloComposable.UseQueryOptions<GetUsersQuery, GetUsersQueryVariables>
    | VueCompositionApi.Ref<
        VueApolloComposable.UseQueryOptions<
          GetUsersQuery,
          GetUsersQueryVariables
        >
      >
    | ReactiveFunction<
        VueApolloComposable.UseQueryOptions<
          GetUsersQuery,
          GetUsersQueryVariables
        >
      > = {}
) {
  return VueApolloComposable.useQuery<GetUsersQuery, GetUsersQueryVariables>(
    GetUsersDocument,
    variables,
    options
  );
}
export function useGetUsersLazyQuery(
  variables:
    | GetUsersQueryVariables
    | VueCompositionApi.Ref<GetUsersQueryVariables>
    | ReactiveFunction<GetUsersQueryVariables> = {},
  options:
    | VueApolloComposable.UseQueryOptions<GetUsersQuery, GetUsersQueryVariables>
    | VueCompositionApi.Ref<
        VueApolloComposable.UseQueryOptions<
          GetUsersQuery,
          GetUsersQueryVariables
        >
      >
    | ReactiveFunction<
        VueApolloComposable.UseQueryOptions<
          GetUsersQuery,
          GetUsersQueryVariables
        >
      > = {}
) {
  return VueApolloComposable.useLazyQuery<
    GetUsersQuery,
    GetUsersQueryVariables
  >(GetUsersDocument, variables, options);
}
export type GetUsersQueryCompositionFunctionResult =
  VueApolloComposable.UseQueryReturn<GetUsersQuery, GetUsersQueryVariables>;
